### PR TITLE
General overhaul

### LINKED ISSUE #4: Glider effects stay after death
The lower gravity effect that comes when gliding with the glider can stay even after death when you jump on TNT while gliding.

To reproduce this bug:

Make a tnt tower, go on top, and once you lit it up, jump 4.5 - 3 seconds after and you will die -or explode with the tnt- after all this the low gravity effect stays even after the death, and even a speed boost is acquired.

This is due to the fact that the glider item is an entity, and when being destroyed by, for instance, TNT, so the physics of low gravity is kept.

you'd basically just have to invoke the correct detach method when the player has died

### LINKED ISSUE #6: server crash init.lua:126: attempt to index local 'luaent' (a nil value)
2021-09-16 17:19:34: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'glider' in callback item_OnUse(): /opt/minetest/bin/../mods/glider/init.lua:126: attempt to index local 'luaent' (a nil value)
2021-09-16 17:19:34: ERROR[Main]: stack traceback:
2021-09-16 17:19:34: ERROR[Main]: 	/opt/minetest/bin/../mods/glider/init.lua:126: in function </opt/minetest/bin/../mods/glider/init.lua:119>

glider latest master
minetest latest master 5.5.0-dev
mietetest_game latest master

### LINKED ISSUE #7: Server crashes when exiting game while still on the glider
This is the error according to the debug:

`2022-05-22 09:48:36: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'glider' in callback luaentity_Step(): .../staging/worlds/world/worldmods/glider/init.lua:47: attempt to index local 'driver' (a nil value)
2022-05-22 09:48:36: ERROR[Main]: stack traceback:
2022-05-22 09:48:36: ERROR[Main]: 	...staging/worlds/world/worldmods/glider/init.lua:47: in function <.../staging/worlds/world/worldmods/glider/init.lua:10>
`

### PR DESCRIPTION
**Pull request by SwissalpS**
-Patches various bugs
-Adds coloured gliders
-More settings
-FLAK support
-Hook for other mods to influence flight-permissions
-New textures to easily differentiate from [hangglider]
-Adds sounds
-Glider can be made to wear-out from damage and usages
-Adds HUD for basic pilot instrument flight
-Support for Mineclone
-And more....

closes #4
closes #6
closes #7

### CODE REVIEW

**Comment by Maverick2797** [comment]
Love the work. Some small things I've noticed with the hud:

- The hud seems to "jitter" when rotating due to the decimals disappearing when the angle is a whole number. Is it possible to pad the value with a trailing zero to minimise this?
- "vV" and "v" seem arbitrary unless you understand that they're "Vertical Velocity" and "(Horizontal) Velocity" respectively. Maybe "Climb Rate" and "Airspeed" instead?
- Perhaps a label on the rocket cooldown? It's currently just an unexplained countdown

Possibly some less-small things related to the physics:

- Opening the glider at high velocity (only tested by freefalling so far) can sometimes cause instant death
- If the player is killed by overspeed (ie freefalling then opens the glider as above) the player is sometimes also damaged when they respawn
- The glider can still climb higher than its initial launch altitude without using rockets after barely falling off a high enough cliff (ie without jumping, running or even walking.) Maybe some sort of climb-to-drag ratio to minimise this? Or just chalk it up to a good pilot being able to find lift? idk

**Comment by SwissalpS** [comment]
Many thanks for the valuable feedback.

> * The hud seems to "jitter" when rotating due to the decimals disappearing when the angle is a whole number. Is it possible to pad the value with a trailing zero to minimise this?

Yes, simple enough to do. I actually had it without decimals and only added them for debugging. Minetest isn't designed to be a flightsim and the HUD is just to help out a little. I don't think players need decimals in the heading indicator. A compass in the hotbar should be just fine.

> * "vV" and "v" seem arbitrary unless you understand that they're "Vertical Velocity" and "(Horizontal) Velocity" respectively. Maybe "Climb Rate" and "Airspeed" instead?

Yes, kindof. Both values are quite arbitrary but do help pilots understand why their glider is behaving the way it does. (v is actually speed factor multiplied to all directions). Your suggested labels are correct. I didn't use them because the first complaint from players is: "Ugh, the HUD is covering my view". Also translations in mind, I tried to go for some ISO standard short labels. Players with small screens quickly have overflows.
Possibly a solution would be to add a chatcommand to toggle HUD and provide options on verbosity. (Originally I had vV only as +, - or =)

> * Perhaps a label on the rocket cooldown? It's currently just an unexplained countdown

Yeah, I was thinking of a coloured horizontal bar and that players would notice soon enough what it meant. I'll consider it again.

> Possibly some less-small things related to the physics:

Disclaimer: I didn't change anything on the physics.

> * Opening the glider at high velocity (only tested by freefalling so far) can sometimes cause instant death

Seems reasonable to me. Something similar would happen if one found a way to do that IRL :D This mod is not the [hangglider] mod which is designed to break falls while this mod is a delta glider (I really want to rename this mod to that). Delta gliders are not safety devices, rather lightweight fixed wing aircraft.

> * If the player is killed by overspeed (ie freefalling then opens the glider as above) the player is sometimes also damaged when they respawn

That isn't unique to this mod. It happens on occasion with various mods. I'll call it an engine issue.

> * The glider can still climb higher than its initial launch altitude without using rockets after barely falling off a high enough cliff (ie without jumping, running or even walking.) Maybe some sort of climb-to-drag ratio to minimise this? Or just chalk it up to a good pilot being able to find lift? idk

I am unable to reproduce that (starting without moving). Maybe my hardware is too sluggish and old. With a running start, I can rise higher and I did consider that a good thing. It keeps the gap between [hangglider] and [(delta)glider] wide enough for servers to consider using both. Also it motivates players to use this glider at all, it's hard enough to even land safely. This mod is quite dangerous as it is, I consider it a good feature that one can actually gain altitude if one is skilled enough.

**Comment by SwissalpS** [comment]
Looking at heading more closely I noticed that flying in counterclockwise circles it is accurate. However flying in clockwise circles it becomes negative!

I'm torn between dropping heading information and fixing it. It's the least important of
all the HUD info and was added more as a gimmick.

**Comment by CBugDCoder** [comment]
@SwissalpS Thank you so much for all the work that you have put into this. I have been busy with college so have stepped back from the Minetest community for the past couple years. I am glad to see my mod getting some love and a fresh life. After I playtest your patch, I will merge it into the main repository. I like the name Delta Gliders I think renaming the actual mod will be more complicated than desired and will break alot of worlds. Therefore, I will rename the ContentDB page to Delta Gliders and call it even.

**Comment by SwissalpS** [comment]
It has been a while, I don't remember if I added everything to this branch.
Maybe just for good measure, you'll compare to my master branch to see if anything other than the rename has changed there.
https://github.com/SwissalpS/minetest_deltaglider/tree/master

**Comment by SwissalpS** [comment]
(I'm glad you like the changes and I'm especially glad that you are back :D I was about to look for someone to maintain this.)

**Comment by CBugDCoder** [comment]
You did add a couple more things to the master branch, namely translations. If you could add all the changes you made to the master branch to the main repo, then I will merge the request. Include the full rename of the mod. I will figure out how to rename the mod on Content DB after the PR is merged. I also added you as a collaborator on this repository. I do not have time to maintain it and do not foresee myself getting back into the MT modding community anytime in the near future.

**Comment by SwissalpS** [comment]
> If you could add all the changes you made to the master branch to the main repo, then I will merge the request. Include the full rename of the mod.

In that case it would be easiest for me to PR the master/main branch of my fork.

> I do not have time to maintain it and do not foresee myself getting back into the MT modding community anytime in the near future.

Then we had better ask an org like https://github.com/mt-mods to adopt it.

**Comment by CBugDCoder** [comment]
> Then we had better ask an org like https://github.com/mt-mods to adopt it.

You are more than welcome to do that. I enjoyed building mods and being in the MT community while I was in High Schoo, but that time is past. With this total overhaul, glider is as much your mod as it is mine now. If you do not want to be the primary maintainer of it, Feel free to find someone who will.

**Comment by SwissalpS** [comment]
@CBugDCoder I don't have permission to rename the repo, that'll be something you need to do.

**Comment by CBugDCoder** [comment]
It has been renamed. Thank you for everything!

**Pull request closed without merging**
