### PR TITLE
Update physics

### LINKED ISSUE #1: Glider is too fast
Hello, I really like this mod. That only problem is it can get a very high velocity. So them I suggest reduce the max velocity and add it as settingstypes

### PR DESCRIPTION
**Pull request by CBugDCoder**
The physics was previously unrealistic at best and downright broken at worst. I aim to fix many of these problems in this PR. This should fix #1.

### CODE REVIEW

**Comment by CBugDCoder** [comment]
Rebased

**Comment by BruceMustache** [comment]
Nice, what missing to merge it to master?

**Comment by CBugDCoder** [comment]
Just testing.

**Comment by CBugDCoder** [comment]
Sorry for the long delay. I will merge this now.

**Pull request merged**
